# Generated by Django 4.0.5 on 2023-07-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                
                ('title', models.CharField(max_length=50)),
                ('author',models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='book/pdfs', max_length=100)),
                ('covers', models.ImageField(upload_to='book/covers', height_field=None, width_field=None, max_length=None)),
            ],
    
    
        ),
    ]
