# Generated by Django 4.0.5 on 2023-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_uploadedpdf_delete_file_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('book', models.FileField(upload_to='')),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedPDF',
        ),
    ]
