# Generated by Django 4.0.5 on 2023-07-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_pdf_delete_uploadedpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='books/pdfs')),
                ('cover', models.ImageField(upload_to='books/covers')),
            ],
        ),
        migrations.DeleteModel(
            name='pdf',
        ),
    ]
