# Generated by Django 4.0.5 on 2023-07-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='flipkart_url',
            field=models.URLField(blank=True),
        ),
    ]
