# Generated by Django 4.0.5 on 2023-08-12 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_review_delete_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
