# Generated by Django 4.0.5 on 2023-09-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_selfhelp_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfhelp_book',
            name='language',
            field=models.CharField(default='selfhelp', max_length=50),
        ),
    ]
