# Generated by Django 4.0.5 on 2023-09-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_selfhelp_book_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHILDREN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=10)),
                ('pdf', models.FileField(blank=True, upload_to='book/pdfs')),
                ('cover', models.ImageField(upload_to='book/covers')),
                ('flipkart_url', models.URLField(blank=True)),
                ('language', models.CharField(default='children', max_length=50)),
            ],
        ),
    ]
