# Generated by Django 4.2.3 on 2023-10-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('concept', models.CharField(max_length=255)),
                ('page_number', models.PositiveIntegerField()),
            ],
        ),
    ]
